(source gnu)
(source melpa)
(source marmalade)

(depends-on "anything")
(depends-on "color-theme")
(depends-on "flycheck")
(depends-on "flymake-json")
(depends-on "flymake-ruby")
(depends-on "flymake-easy")
(depends-on "git-gutter")
(depends-on "haml-mode")
(depends-on "jade-mode")
(depends-on "js2-mode")
(depends-on "json-mode")
(depends-on "ruby-block")
(depends-on "ruby-electric")
(depends-on "sass-mode")
(depends-on "sws-mode")
(depends-on "web-mode")

